apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: migrate-transaction-batch-job
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-job-container
            image: your-batch-job-image:latest
          restartPolicy: OnFailure
